name: budget_master
description: "Organize your finances."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  fan_side_drawer: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  window_manager: ^0.2.7
  fl_chart: ^0.68.0
  animated_custom_dropdown: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
